import numpy as np
from sklearn.exceptions import ConvergenceWarning

# just to turn warnings off
import warnings

from spatialize import logging
from spatialize.result import Summarised
from spatialize._parallel import map_chunks
from spatialize.empirical import (FittedModelFactory, _local_target_variance,
                                   _local_target_skewness)
from spatialize.logging import log_message, resolve_callback
from spatialize.viz import plot_colormap_array, PlotStyle

warnings.filterwarnings("ignore", category=ConvergenceWarning)
warnings.filterwarnings("ignore", category=RuntimeWarning)


class ESSResult(Summarised):
    """
    A class to represent the result of Ensemble Spatial Simulation (ESS).

    This class contains the scenarios generated by the Ensemble Spatial Simulation
    method (ESS), based on a set of ESI (Ensemble Spatial Interpolation) samples. It
    provides methods for visualizing and interacting with the simulation scenarios
    generated for a given estimation result.

    Attributes
    ----------
    esi_result
        The result of the Ensemble Spatial Interpolation (ESI) estimation used
        to generate the ESS scenarios.
    scenarios
        A 2D array where each row represents a simulated scenario based on the
        ESI samples.
    desc
        A description of the ESS result, which is used for labeling and identification.

    Methods
    -------
    quick_plot(n_imgs=9, n_cols=3, norm_lims=False, title_prefix="scenario", title=None):
        Plots a quick preview of the ESS scenarios as a grid of colormap images.
    """

    def __init__(self, ess_scenarios, esi_result, desc):
        """
        Initialize an ESSResult instance.

        Parameters
        ----------
        ess_scenarios : ndarray
            The set of simulated ESS scenarios.
        esi_result : ESIResult
            The ESI result used for generating the ESS scenarios.
        desc : str
            A description of the ESS result.
        """
        self.esi_result = esi_result
        self.scenarios = ess_scenarios
        self.desc = desc

    def _summary(self):
        from spatialize import _display
        from spatialize.result import _data_rows
        sc = np.asarray(self.scenarios, dtype=float)
        n_sims = sc.shape[-1] if sc.ndim >= 2 else 1
        rows = [_display.stats_row("estimate", self.esi_result.estimation()),
                _display.stats_row("all scenarios", sc)]
        if sc.ndim >= 2:
            rows.append(_display.stats_row("scenario means", np.nanmean(sc.reshape(-1, n_sims), axis=0)))
        sim = [("scenarios", n_sims), ("description", self.desc or None)]
        return _display.Summary("ESS simulation", blocks=[("kv", "Simulation", sim), ("kv", "Data", _data_rows(self.esi_result)),
                                                          ("table", "Values", _display.STATS_COLUMNS, rows)],
                                footer="scenarios · quick_plot() · esi_result")

    def quick_plot(self, n_imgs=9, n_cols=3, norm_lims=False, title_prefix="scenario", title=None,
                   theme='alges', cmap=None):
        """
        Quickly plot a preview of the ESS scenarios as a grid of colormap images.

        Uses the `plot_colormap_array` function to display the specified
        number of simulated ESS scenarios. Each scenario is represented as an
        image in the grid layout.

        Parameters
        ----------
        n_imgs : int, optional
            The number of ESS scenarios (images) to display, default: 9.
        n_cols : int, optional
            The number of columns in the grid layout, default: 3.
        norm_lims : bool, optional
            Whether to normalize the values of the scenarios based on the
            reference map, default: False.
        title_prefix : str, optional
            The prefix to use in the subplot titles (e.g., "scenario 1",
            "scenario 2"), default: "scenario".
        title : str, optional
            The title for the entire plot. Defaults to None, which uses the
            `desc` attribute.
        theme : str, optional
            Theme name. Available: 'whitegrid', 'darkgrid', 'white', 'dark',
            'alges', 'minimal', 'publication'. Default: 'alges'.
        cmap : str or Colormap, optional
            Colormap for the plot. If None, uses theme default.

        Returns
        -------
        matplotlib.figure.Figure
            A figure containing the grid of ESS scenario plots.
        """
        if title is None:
            title = self.desc

        with PlotStyle(theme=theme, cmap=cmap) as style:
            return plot_colormap_array(self.scenarios, n_imgs=n_imgs,
                                       n_cols=n_cols, norm_lims=norm_lims,
                                       xi_locations=self.esi_result._xi,
                                       reference_map=self.esi_result.estimation(),
                                       title_prefix=title_prefix,
                                       title=title,
                                       cmap=style.cmap)


def ess_sample(esi_result,
               n_sims=100,
               fitted_model_factory=None,
               desc=None,
               callback=None):
    """
    Generate simulated scenarios from Ensemble Spatial Interpolation (ESI) samples using probabilistic models.

    This function takes ESI (Ensemble Spatial Interpolation) samples from the
    provided ``esi_result``, fits a probabilistic model to each sample using a
    specified model factory, and generates a specified number of simulations
    per sample. Execution can be done serially or in parallel, with real-time
    progress tracking via a callback.

    Parameters
    ----------
    esi_result : object
        An object containing ESI (Ensemble Spatial Interpolation) samples.
        Must implement the method ``esi_samples(raw=True)``, which returns an
        array of shape ``(n_samples, n_features)``. When
        `fitted_model_factory.widening` is set, it must also carry the
        original `points`/`values` used to fit the ESI result.
    n_sims : int, optional
        Number of simulations to generate per ESI sample.
    fitted_model_factory : FittedModelFactory, optional
        A factory for creating fitted probabilistic models per sample. Must
        provide a ``create(...)`` method and define ``point_model_name`` and
        other relevant attributes. Default: a new ``FittedModelFactory()``.
    desc : str, optional
        Textual description for the result. If not provided, it is generated
        based on the model type and simulation parameters.
    callback : callable, optional
        Where the progress and the messages go. Default: ``None``, shown as the session settings
        ``display``, ``progress`` and ``verbosity`` say (:mod:`spatialize.session`). A callable
        receiving the messages of :mod:`spatialize.logging` sends them elsewhere, such as an
        application's own interface, while :func:`~spatialize.logging.singleton_null_callback`
        drops them.

    Returns
    -------
    ESSResult
        An object containing the simulated scenarios, the original ESI
        result, and a textual description.

    Raises
    ------
    ValueError
        If the model type specified in
        ``fitted_model_factory.point_model_name`` is not one of ``"vim"``,
        ``"emm"``, or ``"kde"``.
    ValueError
        If `fitted_model_factory.widening` is set but `esi_result` does not
        carry the original points/values.

    Notes
    -----
    The locations are sampled on several processes (``joblib``) under the
    session settings ``parallel`` and ``num_threads`` (:mod:`spatialize.session`),
    when the work is large enough to repay starting them. Each location draws
    from its own seed, so the scenarios are the same with any number of
    processes.

    A location where model fitting or sampling fails gets NaN scenarios, and a
    warning reports how many locations failed.

    When it runs in parallel, a script should call this function within an
    ``if __name__ == "__main__":`` block to avoid multiprocessing issues
    (especially on Windows and macOS).

    Examples
    --------
    >>> from spatialize.gs.esi import esi_nongriddata
    >>> from spatialize.gs.ess import ess_sample
    >>>
    >>> result = esi_nongriddata(points, values, xi,
    ...                          local_interpolator="idw", alpha=0.9, exponent=2.0)
    >>> ess_result = ess_sample(result, n_sims=100)
    >>> ess_result.scenarios.shape
    (n_xi, 100)
    >>> ess_result.quick_plot()
    """
    callback = resolve_callback(callback)
    if fitted_model_factory is None:
        fitted_model_factory = FittedModelFactory()
    if fitted_model_factory.point_model_name not in {"vim", "emm", "kde"}:
        raise ValueError(f"Unsupported model type: {fitted_model_factory.point_model_name}")

    # work always with the flattened array just to support arbitrary dimensions
    esi_samples = np.array(esi_result.esi_samples(raw=True))

    log_message(logging.logger.debug(f"esi_samples shape: {esi_samples.shape}"))

    target_var_arr = None
    target_skew_arr = None
    if fitted_model_factory.widening:
        if esi_result.points is None or esi_result.values is None:
            raise ValueError(
                "fitted_model_factory.widening requires esi_result to carry the original "
                "points/values (build it with esi_griddata/esi_nongriddata from this version "
                "of spatialize)."
            )
        target_var_arr = _local_target_variance(esi_result.points, esi_result.values,
                                                 esi_result._xi_flat,
                                                 knn=fitted_model_factory.widening_knn)
        if fitted_model_factory.widening == "skew_normal":
            target_skew_arr = _local_target_skewness(esi_result.points, esi_result.values,
                                                      esi_result._xi_flat,
                                                      knn=fitted_model_factory.widening_knn)

    factory = fitted_model_factory

    def rows_data(rows):
        # what a chunk needs: its rows of the ensemble and of the widening targets
        idx = list(rows)
        return (esi_samples[idx, :],
                target_var_arr[idx] if target_var_arr is not None else None,
                target_skew_arr[idx] if target_skew_arr is not None else None)

    def sample_rows(rows, data):
        # one location at a time, each with its own seed (so widening does not draw the same noise
        # everywhere, and the scenarios do not depend on where the location runs)
        samples, target_var, target_skew = data
        model_name = factory.point_model_name
        out = []
        for k, i in enumerate(rows):
            seed = factory.seed + i if factory.seed is not None else None
            try:
                model, _ = factory.create(
                    samples[k, :],
                    target_var=target_var[k] if target_var is not None else None,
                    target_skew=target_skew[k] if target_skew is not None else None,
                    seed=seed)
                if model_name in {"vim", "emm"}:
                    sims = model.sample(n_sims)[0].reshape(n_sims)
                else:
                    # KernelDensity has no constructor-level random_state (unlike GMM/BGM), so its
                    # draw is only reproducible if seeded per call
                    sims = model.sample(n_sims, random_state=seed).reshape(n_sims)
                out.append((sims, None))
            except Exception as e:
                out.append((None, f"{type(e).__name__}: {e}"))
        return out

    results = map_chunks(sample_rows, esi_samples.shape[0], data_for=rows_data, callback=callback,
                         desc="simulating the local laws")
    failed = [(i, r[1]) for i, r in enumerate(results) if r[0] is None]
    if failed:
        log_message(logging.logger.warning(
            f"sampling failed at {len(failed)} of {len(results)} locations, whose "
            f"scenarios are NaN (first failure, location {failed[0][0]}: {failed[0][1]})"))
    scenarios = np.stack([r[0] if r[0] is not None else np.full(n_sims, np.nan) for r in results])

    if desc is None:
        if fitted_model_factory.point_model_name == "kde":
            desc = f"{n_sims}sims_kde_{fitted_model_factory.kernel}"
        else:
            desc = f"{n_sims}sims_{fitted_model_factory.point_model_name}_{fitted_model_factory.n_components}_components"

    return ESSResult(scenarios, esi_result, desc)
