import threading
from multiprocessing import Manager

import numpy as np
from joblib import Parallel, delayed
from sklearn.mixture import BayesianGaussianMixture, GaussianMixture
from sklearn.neighbors import KernelDensity
from sklearn.exceptions import ConvergenceWarning

# just to turn warnings off
import warnings

from spatialize import logging
from spatialize.empirical import (FittedModelFactory, EmpiricalModel, _local_target_variance,
                                   _local_target_skewness)
from spatialize.logging import log_message, default_singleton_callback
from spatialize.viz import plot_colormap_array, PlotStyle

warnings.filterwarnings("ignore", category=ConvergenceWarning)
warnings.filterwarnings("ignore", category=RuntimeWarning)


class ESSResult:
    """
    A class to represent the result of Ensemble Spatial Simulation (ESS).

    This class contains the scenarios generated by the Ensemble Spatial Simulation
    method (ESS), based on a set of ESI (Ensemble Spatial Interpolation) samples. It
    provides methods for visualizing and interacting with the simulation scenarios
    generated for a given estimation result.

    Attributes
    ----------
    esi_result
        The result of the Ensemble Spatial Interpolation (ESI) estimation used
        to generate the ESS scenarios.
    scenarios
        A 2D array where each row represents a simulated scenario based on the
        ESI samples.
    desc
        A description of the ESS result, which is used for labeling and identification.

    Methods
    -------
    quick_plot(n_imgs=9, n_cols=3, norm_lims=False, title_prefix="scenario", title=None):
        Plots a quick preview of the ESS scenarios as a grid of colormap images.
    """

    def __init__(self, ess_scenarios, esi_result, desc):
        """
        Initialize an ESSResult instance.

        Parameters
        ----------
        ess_scenarios : ndarray
            The set of simulated ESS scenarios.
        esi_result : ESIResult
            The ESI result used for generating the ESS scenarios.
        desc : str
            A description of the ESS result.
        """
        self.esi_result = esi_result
        self.scenarios = ess_scenarios
        self.desc = desc

    def __repr__(self):
        return str(self.desc)

    def quick_plot(self, n_imgs=9, n_cols=3, norm_lims=False, title_prefix="scenario", title=None,
                   theme='alges', cmap=None):
        """
        Quickly plot a preview of the ESS scenarios as a grid of colormap images.

        Uses the `plot_colormap_array` function to display the specified
        number of simulated ESS scenarios. Each scenario is represented as an
        image in the grid layout.

        Parameters
        ----------
        n_imgs : int, optional
            The number of ESS scenarios (images) to display, default: 9.
        n_cols : int, optional
            The number of columns in the grid layout, default: 3.
        norm_lims : bool, optional
            Whether to normalize the values of the scenarios based on the
            reference map, default: False.
        title_prefix : str, optional
            The prefix to use in the subplot titles (e.g., "scenario 1",
            "scenario 2"), default: "scenario".
        title : str, optional
            The title for the entire plot. Defaults to None, which uses the
            `desc` attribute.
        theme : str, optional
            Theme name. Available: 'whitegrid', 'darkgrid', 'white', 'dark',
            'alges', 'minimal', 'publication'. Default: 'alges'.
        cmap : str or Colormap, optional
            Colormap for the plot. If None, uses theme default.

        Returns
        -------
        matplotlib.figure.Figure
            A figure containing the grid of ESS scenario plots.
        """
        if title is None:
            title = self.desc

        with PlotStyle(theme=theme, cmap=cmap) as style:
            return plot_colormap_array(self.scenarios, n_imgs=n_imgs,
                                       n_cols=n_cols, norm_lims=norm_lims,
                                       xi_locations=self.esi_result._xi,
                                       reference_map=self.esi_result.estimation(),
                                       title_prefix=title_prefix,
                                       title=title,
                                       cmap=style.cmap)


def ess_sample(esi_result,
               n_sims=100,
               fitted_model_factory=FittedModelFactory(),
               desc=None,
               n_jobs=-1,
               callback=default_singleton_callback):
    """
    Generate simulated scenarios from Ensemble Spatial Interpolation (ESI) samples using probabilistic models.

    This function takes ESI (Ensemble Spatial Interpolation) samples from the
    provided ``esi_result``, fits a probabilistic model to each sample using a
    specified model factory, and generates a specified number of simulations
    per sample. Execution can be done serially or in parallel, with real-time
    progress tracking via a callback.

    Parameters
    ----------
    esi_result : object
        An object containing ESI (Ensemble Spatial Interpolation) samples.
        Must implement the method ``esi_samples(raw=True)``, which returns an
        array of shape ``(n_samples, n_features)``. When
        `fitted_model_factory.widening` is set, it must also carry the
        original `points`/`values` used to fit the ESI result.
    n_sims : int, optional
        Number of simulations to generate per ESI sample.
    fitted_model_factory : FittedModelFactory, optional
        A factory for creating fitted probabilistic models per sample. Must
        provide a ``create(...)`` method and define ``point_model_name`` and
        other relevant attributes.
    desc : str, optional
        Textual description for the result. If not provided, it is generated
        based on the model type and simulation parameters.
    n_jobs : int, optional
        Number of parallel jobs to use. Set to ``1`` for serial execution or
        ``-1`` to use all available CPUs.
    callback : callable, optional
        A callback function for progress reporting. Expected to support
        ``logging.progress.init``, ``inform``, and ``stop`` methods.

    Returns
    -------
    ESSResult
        An object containing the simulated scenarios, the original ESI
        result, and a textual description.

    Raises
    ------
    ValueError
        If the model type specified in
        ``fitted_model_factory.point_model_name`` is not one of ``"vim"``,
        ``"emm"``, or ``"kde"``.
    ValueError
        If `fitted_model_factory.widening` is set but `esi_result` does not
        carry the original points/values.

    Notes
    -----
    This function supports parallel execution using ``joblib.Parallel`` and
    includes a separate thread for real-time progress monitoring. It is
    designed for large-scale scenario generation from spatial ensemble data.

    If model fitting or sampling fails for a given sample, its corresponding
    scenario row is replaced with zeros.

    When using ``n_jobs != 1``, this function must be called within an
    ``if __name__ == "__main__":`` block to avoid multiprocessing issues
    (especially on Windows and macOS).

    Examples
    --------
    >>> from spatialize.gs.esi import esi_nongriddata
    >>> from spatialize.gs.ess import ess_sample
    >>>
    >>> result = esi_nongriddata(points, values, xi,
    ...                          local_interpolator="idw", alpha=0.9, exponent=2.0)
    >>> ess_result = ess_sample(result, n_sims=100)
    >>> ess_result.scenarios.shape
    (n_xi, 100)
    >>> ess_result.quick_plot()
    """
    # work always with the flattened array just to support arbitrary dimensions
    esi_samples = np.array(esi_result.esi_samples(raw=True))

    log_message(logging.logger.debug(f"esi_samples shape: {esi_samples.shape}"))

    target_var_arr = None
    target_skew_arr = None
    if fitted_model_factory.widening:
        if esi_result.points is None or esi_result.values is None:
            raise ValueError(
                "fitted_model_factory.widening requires esi_result to carry the original "
                "points/values (build it with esi_griddata/esi_nongriddata from this version "
                "of spatialize)."
            )
        target_var_arr = _local_target_variance(esi_result.points, esi_result.values,
                                                 esi_result._xi_flat,
                                                 knn=fitted_model_factory.widening_knn)
        if fitted_model_factory.widening == "skew_normal":
            target_skew_arr = _local_target_skewness(esi_result.points, esi_result.values,
                                                      esi_result._xi_flat,
                                                      knn=fitted_model_factory.widening_knn)

    def run_serial():
        scenarios = np.empty([esi_samples.shape[0], n_sims])
        callback(logging.progress.init(esi_samples.shape[0], 1))
        for esi_sample_idx in range(esi_samples.shape[0]):
            target_var = target_var_arr[esi_sample_idx] if target_var_arr is not None else None
            target_skew = target_skew_arr[esi_sample_idx] if target_skew_arr is not None else None
            # derive a per-location seed so widening doesn't draw identical noise at every
            # sample (mirrors the `self.seed + i` pattern used elsewhere, e.g. gs/esmi/_main.py)
            location_seed = (fitted_model_factory.seed + esi_sample_idx
                              if fitted_model_factory.seed is not None else None)
            model, _ = fitted_model_factory.create(esi_samples[esi_sample_idx, :],
                                                    target_var=target_var, target_skew=target_skew,
                                                    seed=location_seed)

            # sampling from the fitted model
            if fitted_model_factory.point_model_name in {"vim", "emm"}:
                s = model.sample(n_sims)[0].reshape(1, n_sims)[0]
            elif fitted_model_factory.point_model_name == "kde":
                # KernelDensity has no constructor-level random_state (unlike GMM/BGM), so
                # its draw is only reproducible if seeded per call.
                s = model.sample(n_sims, random_state=location_seed).reshape(1, n_sims)[0]
            else:
                raise ValueError(f"Unsupported model type: {fitted_model_factory.point_model_name}")

            scenarios[esi_sample_idx, :] = s[:]
            callback(logging.progress.inform())
        callback(logging.progress.stop())
        return scenarios

    # to run in parallel ------------------------------------------------------------------------
    def sample_single_scenario(idx, sample_row, n_sims, model_factory, target_var, target_skew, seed, progress_q):
        try:
            model, _ = model_factory.create(sample_row, target_var=target_var, target_skew=target_skew,
                                             seed=seed)

            # Sample based on model type
            if model_factory.point_model_name in {"vim", "emm"}:
                sims = model.sample(n_sims)[0].reshape(n_sims)
            elif model_factory.point_model_name == "kde":
                sims = model.sample(n_sims, random_state=seed).reshape(n_sims)
            else:
                raise ValueError(f"Unsupported model type: {model_factory.point_model_name}")

            if progress_q:
                progress_q.put(1)
            return idx, sims

        except Exception as e:
            logging.logger.debug(f"Sampling failed for sample[{idx}]: {e}")
            if progress_q:
                progress_q.put(1)
            return idx, None

    def run_parallel():
        def progress_monitor(queue, total, cb):
            count = 0
            cb(logging.progress.init(total, 1))
            while count < total:
                queue.get()
                count += 1
                cb(logging.progress.inform())
            cb(logging.progress.stop())

        with Manager() as manager:
            progress_queue = manager.Queue()

            monitor_thread = threading.Thread(
                target=progress_monitor,
                args=(progress_queue, esi_samples.shape[0], callback),
                daemon=True
            )
            monitor_thread.start()

            results = Parallel(n_jobs=n_jobs, backend='loky')(
                delayed(sample_single_scenario)(
                    i, esi_samples[i, :], n_sims, fitted_model_factory,
                    target_var_arr[i] if target_var_arr is not None else None,
                    target_skew_arr[i] if target_skew_arr is not None else None,
                    fitted_model_factory.seed + i if fitted_model_factory.seed is not None else None,
                    progress_queue
                )
                for i in range(esi_samples.shape[0])
            )

            monitor_thread.join()

        # Sort results and construct the scenarios array
        sorted_results = sorted(results, key=lambda x: x[0])
        valid_scenarios = [r[1] if r[1] is not None else np.zeros(n_sims) for r in sorted_results]
        scenarios = np.stack(valid_scenarios)

        return scenarios

    if n_jobs == 1:
        scenarios = run_serial()
    else:
        scenarios = run_parallel()

    if desc is None:
        if fitted_model_factory.point_model_name == "kde":
            desc = f"{n_sims}sims_kde_{fitted_model_factory.kernel}"
        else:
            desc = f"{n_sims}sims_{fitted_model_factory.point_model_name}_{fitted_model_factory.n_components}_components"

    return ESSResult(scenarios, esi_result, desc)
